name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17.0'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint # Certifique-se de ter um script lint no seu package.json

      - name: Run tests
        run: npm test # Certifique-se de ter um script test no seu package.json

      - name: Generate test coverage
        run: npm run coverage # Certifique-se de ter um script coverage no seu package.json

      - name: Upload coverage results
        uses: actions/upload-artifact@v3 # Atualizando para a versão v3
        with:
          name: coverage-results
          path: coverage/ # Ajuste conforme o diretório onde os resultados de cobertura são gerados
