name: Linter and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17.0'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: List test files
        run: find src -name "*.test.js" # Lista arquivos de teste para verificação

      - name: Run tests
        run: npm test -- --verbose # Executa os testes com saída verbosa

      - name: Generate test coverage
        run: npm run coverage

      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage-results
          path: coverage/ # Ajuste conforme o diretório onde os resultados de cobertura são gerados
